### ISSUE TITLE
weather api keys

### ISSUE THREAD

**Issue by tarzanek** [trasigor/Sketchy-App-for-FitBit#1]
Hi Igor,
I don't know how many requests your api key can provide, but would it make sense for people to provide their own api key?
(add it to settings and if filled use it, instead of proxy to your server?)

and thank you for a great watch face, good stuff!

thnx
L

**Comment by tarzanek** [comment]
Or even better - I saw this:
https://www.npmjs.com/package/fitbit-weather
so it could be even better to compile with weather (and add the API key to setting anyways) and use data that is on device anyways instead of custom calls(I see that for yahoo weather provider you'd still need your code).
What do you think?

**Comment by trasigor** [comment]
I thought about adding field for API key, the only thing that there is a really little part of users know what it is and how to use it. It might be great for you to control your requests, but not for the most users. But still, I may add such field in the future.
Regarding package, it has less weather conditions then weather providers. And issue with yahoo weather should be fixed in the latest update. They permitted of using their service without API key and it takes few days to get approve for a new API key, so all requests to yahoo weather now go through my own server. It is also a good point to fix problems on theiir future updates. For me personally would be better if every user used own api key, but users not use such software, only programmers. So first I'm trying to make the app easy in use and then add some custom features when have time for this.

**Comment by tarzanek** [comment]
I have now flipped from git build and sidedeploy to your new official release now
all works 😍 

obviously once you'll add the API key I can switch to own key, after all there is most probably a quota and I don't want to use yours, I am already happy you shared this watchface and its code (RESPECT!)

thank you, my wife loves this face (and I also think it's the best watch faces on the marker :-) ), keep it up
Lubos
